# strong scaling test on small machines

strong-1:
	make clean
	ln -s strong-1 input
#	$(OPENMPIV)/bin/mpirun -np 1 $(HOME)/bin/paris > out-strong-1 2>err-strong-1
	mpirun -np 1 $(HOME)/bin/paris > out-strong-1 2>err-strong-1


strong-8:
	make clean
	ln -s input-strong-8 input
#	$(OPENMPIV)/bin/mpirun -np 8 $(HOME)/bin/paris > out-strong-8 2>err-strong-8
	mpirun -np 8 $(HOME)/bin/paris > out-strong-8 2>err-strong-8


strong-32:
	make clean
	ln -s input-strong-32 input
#	$(OPENMPIV)/bin/mpirun -np 32 $(HOME)/bin/paris > out-strong-32 2>err-strong-32
	mpirun -np 32 $(HOME)/bin/paris > out-strong-32 2>err-strong-32


#------------------

clean:
	rm -fr  stats track input *~ #*

allclean: clean
	  rm -fr out* err*

